#!/bin/bash

# COMANDOS PARA EXECUTAR NO SERVIDOR APÓS UPLOAD
# ==============================================
# Execute estes comandos via SSH no seu servidor

echo "🔧 COMANDOS PARA EXECUTAR NO SERVIDOR"
echo "====================================="
echo ""

echo "📋 1. PREPARAÇÃO INICIAL"
echo "------------------------"
echo "# Navegue para o diretório do projeto"
echo "cd /home/usadosar/public_html/bc"
echo ""
echo "# Faça backup do sistema atual"
echo "cp -r . ../backup-bc-sistema-\$(date +%Y%m%d-%H%M%S)"
echo ""

echo "📋 2. UPLOAD DOS ARQUIVOS"
echo "------------------------"
echo "# Descompacte os arquivos (após upload via FTP)"
echo "tar -xzf deploy-bc-sistema.tar.gz"
echo ""
echo "# OU se usar rsync/scp:"
echo "# rsync -avz --delete ./deploy-ready/ usuario@servidor:/home/usadosar/public_html/bc/"
echo ""

echo "📋 3. INSTALAR DEPENDÊNCIAS"
echo "---------------------------"
echo "# Instalar dependências do Composer"
echo "composer install --optimize-autoloader --no-dev"
echo ""
echo "# Se não tiver composer globalmente:"
echo "# php composer.phar install --optimize-autoloader --no-dev"
echo ""

echo "📋 4. CONFIGURAR AMBIENTE"
echo "------------------------"
echo "# Verificar se o .env existe (não substituir!)"
echo "if [ ! -f .env ]; then"
echo "    cp .env.example .env"
echo "    echo 'Configure o .env com suas credenciais'"
echo "fi"
echo ""
echo "# Gerar chave da aplicação (se necessário)"
echo "php artisan key:generate"
echo ""

echo "📋 5. CONFIGURAR PERMISSÕES"
echo "--------------------------"
echo "# Definir permissões corretas"
echo "chmod -R 755 storage"
echo "chmod -R 755 bootstrap/cache"
echo "chown -R \$USER:www-data storage bootstrap/cache"
echo ""
echo "# Para servidores compartilhados:"
echo "# chmod -R 777 storage bootstrap/cache"
echo ""

echo "📋 6. EXECUTAR MIGRAÇÕES"
echo "-----------------------"
echo "# Executar migrações (CUIDADO: fazer backup do banco antes!)"
echo "php artisan migrate --force"
echo ""
echo "# Se quiser restaurar o backup do banco:"
echo "# mysql -u usadosar_lara962 -p usadosar_lara962 < backup_banco.sql"
echo ""

echo "📋 7. OTIMIZAR CACHE"
echo "-------------------"
echo "# Limpar caches antigos"
echo "php artisan config:clear"
echo "php artisan cache:clear"
echo "php artisan view:clear"
echo "php artisan route:clear"
echo ""
echo "# Gerar novos caches (produção)"
echo "php artisan config:cache"
echo "php artisan route:cache"
echo "php artisan view:cache"
echo ""

echo "📋 8. VERIFICAÇÕES FINAIS"
echo "------------------------"
echo "# Testar se o sistema está funcionando"
echo "php artisan --version"
echo ""
echo "# Verificar conectividade com banco"
echo "php artisan migrate:status"
echo ""
echo "# Testar rota principal"
echo "curl -I http://seudominio.com/bc"
echo ""

echo "📋 9. MONITORAMENTO"
echo "------------------"
echo "# Verificar logs em caso de erro"
echo "tail -f storage/logs/laravel.log"
echo ""
echo "# Verificar permissões se houver erro"
echo "ls -la storage/ bootstrap/cache/"
echo ""

echo "🎯 DEPLOY FINALIZADO!"
echo "==================="
echo ""
echo "✅ Acesse: http://seudominio.com/bc"
echo "✅ Teste todas as funcionalidades"
echo "✅ Verifique se os gráficos estão carregando"
echo "✅ Teste a responsividade no mobile"
echo ""
